inputNPfiles:
    - "PAS01578.dorado0.7.3.bmdna_r10.4.1_e8.2_400bps_5.0.0_fast.sim"
    - "PAS01578.dorado0.7.3.bmdna_r10.4.1_e8.2_400bps_5.0.0_hac.sim"
    - "PAS01578.dorado0.7.3.bmdna_r10.4.1_e8.2_400bps_5.0.0_hac.dup"
    - "PAS01578.dorado0.7.3.bmdna_r10.4.1_e8.2_400bps_5.0.0_sup.sim"
    - "PAS01578.dorado0.7.3.bmdna_r10.4.1_e8.2_400bps_5.0.0_sup.dup"
npreads:
    - 10000
    - 20000
    - 30000
    - 40000
    - 50000
    - 60000
    - 70000
    - 80000
    - 90000
    - 100000
    - 150000
    - 200000
    - 500000
    - 1000000
reffiles:
    - B.subtilis_hifiasm
    - C.neoformans_hifiasm
    - E.coli_hifiasm
    - E.faecalis_hifiasm
    - L.monocytogenes_hifiasm
    - P.aeruginosa_hifiasm
    - S.aureus_hifiasm
    - S.cerevisiae_hifiasm
    - S.enterica_hifiasm
asmtypes:
    - flye
assembly_threads:
     20
assembly_mb:
     100000

