name: microbench_zymohmw_basecalling-benchmarks
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3.0  # Use an older version of r-base
  - r-tidyverse=2.0.0
  - r-gridextra=2.3
  - r-kableextra=1.4.0
  - r-rmarkdown=2.28
  - python=3.11  # Use a newer version of Python
  - pandoc=3.4
  - flye=2.9.5
  - quast=5.2.0
  - fastani=1.33
  - seqtk=1.3
  - bioawk=1.0
  - samtools=1.16.1
  - snakemake=8.20.3
  - nanoplot
  - minimap2=2.28
  - bamtools=2.5.2
  - bcftools=1.21
